AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: GSCDataLoader
Resources:
  GSCDataLoader:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs8.10
      Handler: index.handler
      Timeout: 15
      Environment:
        Variables:
          CLIENT_EMAIL: your google client email
          PRIVATE_KEY: |
            -----BEGIN PRIVATE KEY-----
            your google private key
            -----END PRIVATE KEY-----
          SITE_LIST: https://www.bidu.com.br,https://www.thinkseg.com
